package jetbrains.mps.tutorial.calculator.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "Calculator", 0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0x1a52c2aa50cded56L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:f0209c1b-bbf6-447e-9a0f-cd6872a76a90(jetbrains.mps.tutorial.calculator.structure)/1896792429832301910");
    b.version(3);
    b.aggregate("inputField", 0xa52b001e0bd04cdL).target(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd04beL).optional(true).ordered(true).multiple(true).origin("743850410581492941").done();
    b.aggregate("outputField", 0xa52b001e0bd3433L).target(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd3428L).optional(true).ordered(true).multiple(true).origin("743850410581505075").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "InputField", 0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd04beL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:f0209c1b-bbf6-447e-9a0f-cd6872a76a90(jetbrains.mps.tutorial.calculator.structure)/743850410581492926");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "InputFieldReference", 0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0c372a3L);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.origin("r:f0209c1b-bbf6-447e-9a0f-cd6872a76a90(jetbrains.mps.tutorial.calculator.structure)/743850410581914275");
    b.version(3);
    b.associate("field", 0xa52b001e0c372a4L).target(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd04beL).optional(false).origin("743850410581914276").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.mps.tutorial.calculator", "OutputField", 0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd3428L);
    b.class_(false, false, false);
    b.origin("r:f0209c1b-bbf6-447e-9a0f-cd6872a76a90(jetbrains.mps.tutorial.calculator.structure)/743850410581505064");
    b.version(3);
    b.aggregate("expression", 0xa52b001e0c322feL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("743850410581893886").done();
    return b.create();
  }
}
