package jetbrains.mps.tutorial.calculator.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class InputFieldReference_SubstituteMenu extends SubstituteMenuBase {
  public InputFieldReference_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for InputFieldReference. Generated from implicit smart reference attribute.", new SNodePointer("r:f0209c1b-bbf6-447e-9a0f-cd6872a76a90(jetbrains.mps.tutorial.calculator.structure)", "743850410581914275")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_i4w2se_a(), CONCEPTS.InputFieldReference$aN));
    result.add(new SMP_Subconcepts_i4w2se_b());
    return result;
  }

  public class SMP_ReferenceScope_i4w2se_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_i4w2se_a() {
      super(CONCEPTS.InputFieldReference$aN, LINKS.field$Tk4u, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_i4w2se_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_i4w2se_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "InputFieldReference", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.InputFieldReference$aN);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept InputFieldReference$aN = MetaAdapterFactory.getConcept(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0c372a3L, "jetbrains.mps.tutorial.calculator.structure.InputFieldReference");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink field$Tk4u = MetaAdapterFactory.getReferenceLink(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0c372a3L, 0xa52b001e0c372a4L, "field");
  }
}
