package jetbrains.mps.tutorial.calculator.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class InputFieldReference_Constraints extends BaseConstraintsDescriptor {
  /*package*/ InputFieldReference_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.InputFieldReference$aN, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.field$Tk4u, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return ReferenceScopeProvider.fromHierarchy(CONCEPTS.InputField$Ln, new SNodePointer("r:2f98803f-3ca5-4b91-8af1-3c8f72a8fa50(jetbrains.mps.tutorial.calculator.constraints)", "743850410585169714"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept InputFieldReference$aN = MetaAdapterFactory.getConcept(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0c372a3L, "jetbrains.mps.tutorial.calculator.structure.InputFieldReference");
    /*package*/ static final SConcept InputField$Ln = MetaAdapterFactory.getConcept(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0bd04beL, "jetbrains.mps.tutorial.calculator.structure.InputField");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink field$Tk4u = MetaAdapterFactory.getReferenceLink(0x8b0588535d4d4867L, 0xb7330be50c3342c0L, 0xa52b001e0c372a3L, 0xa52b001e0c372a4L, "field");
  }
}
